name: Minecraft Server CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Java 21 (OpenJDK)
      run: |
        sudo apt update
        sudo apt install -y openjdk-21-jdk
        sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/java-21-openjdk-amd64/bin/java 1
        sudo update-alternatives --set java /usr/lib/jvm/java-21-openjdk-amd64/bin/java

    - name: Verify Java Installation
      run: java -version

    - name: Download Minecraft Server
      run: curl -o server.jar https://piston-data.mojang.com/v1/objects/450698d1863ab5180c25d7c804ef0fe6369dd1ba/server.jar

    - name: Accept EULA
      run: echo 'eula=true' > eula.txt

    - name: Download Ngrok
      run: curl -O "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip"

    - name: Extract Ngrok
      run: unzip ngrok-v3-stable-linux-amd64.zip

    - name: Auth Ngrok
      run: ./ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Start Minecraft Server
      run: |
        nohup java -Xmx4G -Xms4G -jar server.jar nogui &

    - name: Create Ngrok Tunnel
      run: nohup ./ngrok tcp 25565 &

    - name: OP the Player
      run: |
        sleep 30 # Wait for the Minecraft server to fully start
        echo "op IEatHex__" | nc localhost 25565

    - name: Keep Alive
      run: |
        while true; do
          echo "Keeping Minecraft server alive..."
          sleep 60
        done
