name: Minecraft Server CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Java
      run: sudo apt update && sudo apt install openjdk-17-jdk -y

    - name: Download Minecraft Server
      run: curl -o server.jar https://piston-data.mojang.com/v1/objects/450698d1863ab5180c25d7c804ef0fe6369dd1ba/server.jar

    - name: Accept EULA
      run: echo 'eula=true' > eula.txt

    - name: Start Minecraft Server
      run: |
        nohup java -Xmx4G -Xms4G -jar server.jar nogui &

    - name: Create Ngrok Tunnel
      run: nohup ./ngrok tcp 25565 &
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Keep Alive
      run: |
        while true; do
          echo "Keeping Minecraft server alive..."
          sleep 60
        done
